variables:
  GIT_SUBMODULE_STRATEGY: recursive

build:
  stage: build
  tags:
    - dotnet
  script:
    - dotnet build Taoyouh.Mphtxt.sln -c Release
  artifacts:
    paths:
      - Taoyouh.Mphtxt/bin
      - Taoyouh.Mphtxt.Tests/bin
      - Taoyouh.Mphtxt.Tests/obj

test:
  stage: test
  tags:
    - dotnet
  script:
    - dotnet test --no-build --configuration Release Taoyouh.Mphtxt.Tests\Taoyouh.Mphtxt.Tests.csproj